use_frameworks!

source 'https://gitee.com/1210233/SPSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'SPUIKitCategory_Example' do
  pod 'SPUIKitCategory'
  pod 'FMDB'
  pod 'AFNetworking'

  target 'SPUIKitCategory_Tests' do
    inherit! :search_paths

    
  end
end
